### ISSUE TITLE
Add "Sort type" field for MiniParseOverlay

### ISSUE THREAD

**Issue by Marisaaaaaa** [ngld/OverlayPlugin#44] opened 2019-11-21 23:46 UTC
In hibiyasleep's OverlayPlugin, there is a field which allows you to sort entries for overlays like Horizoverlay. I cannot find such an option in this fork and without this option, Horizoverlay won't sort party members by dps order and instead sort them randomly.

**Comment by ngld** [comment] 2019-11-21 23:51
Duplicate of #33.

**Closed as completed by ngld** 2019-11-21 23:51 UTC
