### ISSUE TITLE
Overlays reset scale and position on ACT restart.

### ISSUE THREAD

**Issue by geetarkev** [ngld/OverlayPlugin#58] opened 2019-11-26 23:04 UTC
Since the latest version update, on startup of ACT the scaling for Cactbot and Kagerou is shrunk and they also have their positioning changed from where they were saved. The scaling corrects itself as soon as the overlay is unlocked and dragged.

**Comment by ngld** [comment] 2019-11-26 23:08
This is more or less a duplicate of #13 and caused by missing high DPI support in ACT. Windows tries to scale the overlays itself which just causes them to glitch like you described. Your best bet is to disable the scaling by opening ACT's compatibility settings and setting the scaling mode to `Application`.
You can then use the zoom slider in the overlay settings to scale the overlay.

**Closed as completed** 2019-11-27 00:14 UTC
