### ISSUE TITLE
Missing MS Visual C++ redistributable even after installing it

### ISSUE THREAD

**Issue by Selfen** [ngld/OverlayPlugin#30] opened 2019-11-15 22:35 UTC
Hi,

I'm trying to install the ngld version as hibiya will not be supported soon.
I downloaded the latest version and extracted in a different folder than hibiya one.
When launching ACT I have this message 
![image](https://user-images.githubusercontent.com/57816160/68980182-04b1ba00-0800-11ea-9197-98eef47d4d4e.png)

The thing is it's already installed. I tried doing repare or uninstall/install and it keep showing.
If I cancell the setup, I have this 
![image](https://user-images.githubusercontent.com/57816160/68980343-81dd2f00-0800-11ea-9cd8-ed2b5b2762fc.png)

I didn't had any problem with the hibiya version.

**Comment by ngld** [comment] 2019-11-16 03:47
That message only shows up if `C:\Windows\system32\msvcp140.dll` is missing. That file is part of the redistributable files for Visual Studio 2019. Make sure you have the right version installed (x64, not x86). Installing both is fine as well.

**Comment by Selfen** [comment] 2019-11-16 08:25
Hum that's strange, the dll is here
![image](https://user-images.githubusercontent.com/57816160/68990419-08baf780-0853-11ea-8e59-e0e0dd87a7bf.png)

**Comment by ngld** [comment] 2019-11-17 12:05
The problem is that your file is in `W:\Windows\System32` and not in `C:\Windows\System32`.
I've modified the check to verify that it can load the library instead of looking for a specific file. Does [this build](https://github.com/ngld/OverlayPlugin/files/3855531/OverlayPlugin-0.10.1.zip) solve the issue for you?

**Comment by Selfen** [comment] 2019-11-17 13:53
It solve the problem but now i have this one
There's French inside so I don't know if it's ok for you ><
If it's too hard, maybe i can just make my windows back to C: i guess it will just mess my desktop shortcuts
![image](https://user-images.githubusercontent.com/57816160/69008362-c7f1da00-0949-11ea-97ca-cfb16688807e.png)

**Comment by ngld** [comment] 2019-11-17 14:04
Make sure you load OverlayPlugin before ACTWS and restart ACT. ACTWS has an old version of `SharpCompress` that breaks OverlayPlugin's updater.

**Comment by Selfen** [comment] 2019-11-17 14:15
Worked !
ACT now launched perfectly, I'll install cactbot now then.
So the special build I have now will work for next update ?

**Comment by ngld** [comment] 2019-11-17 14:34
The changes will be included in the next update, yes. I just wanted to make sure the fix worked before releasing a new update.

**Closed as completed by ngld** 2019-11-17 14:34 UTC
Labels: bug

**Comment by Selfen** [comment] 2019-11-17 14:36
Then thanks a lot and keep doing good work !
