### ISSUE TITLE
Custom Labels Missing

### ISSUE THREAD

**Issue by Dreadlow** [ngld/OverlayPlugin#162] opened 2020-09-06 18:06 UTC
Version: 0.16.1.0

Previously had 0.16.0.0

Setup a couple Custom Label overlays for rotation display via jpg/png image. Got the notice for an update today (09/06/2020 at 01:43PM), got the new version, noticed my labels and their keybinds were not working. Looking into the plugin settings and the labels are gone.

Went to create a new one and received exceptions; tried with different names in case the old ones were still there somehow but the name was conflicting; same issue. Unhandled exceptions as follows:

[First Unhandled Exception.txt](https://github.com/ngld/OverlayPlugin/files/5180043/First.Unhandled.Exception.txt)

[Second Unahndled Exception.txt](https://github.com/ngld/OverlayPlugin/files/5180044/Second.Unahndled.Exception.txt)

**Comment by ngld** [comment] 2020-09-08 23:19
This bug was introduced in 0.16.0. The issue was caused by one of the changes in the big overhaul. Due to the change, OverlayPlugin could neither read existing Label overlay configs nor create new configs. This is fixed in a27d2b15cb0a78d2d0584bdc38fd348d4294b76a which will be released in an update tomorrow.

**Closed as completed by ngld** 2020-09-08 23:19 UTC
